import type { Metadata } from "next";
import "./globals.css";
import Background from "./Background";
import Menu from "./Menu";
import { Cormorant_Infant } from "next/font/google";
import CanvasDust from "./CanvasDust";
import { NextIntlClientProvider } from "next-intl";
import Translation from "./Translation";
import { getMessages } from "next-intl/server";
import Loading from "./Loading";
import Scroll from "./Scroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cormorant = Cormorant_Infant({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-cormorant",
});

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${cormorant.variable}`}>
        {/* <Loading /> */}
        <NextIntlClientProvider messages={messages}>
          <Background />
          <CanvasDust />
          <Menu />
          <Translation />
          <div className="mt-[140px]">
            <Scroll>{children}</Scroll>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
